{% set name = "openpathsampling" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openpathsampling-{{ version }}.tar.gz
  sha256: 10660565f73accd0cafd10ce826033f8e8b5c6c7588e6f755336da71dbb645d3

build:
  noarch: python
  script: MPLBACKEND=Agg {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - future
    - psutil
    - numpy
    - scipy
    - pandas
    - netcdf4
    - svgwrite
    - networkx
    - matplotlib-base
    - ujson !=2.*,!=3.*,!=4.0.0,!=4.0.1
    - mdtraj
    - __unix

test:
  imports:
    - openpathsampling
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openpathsampling/openpathsampling
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for path sampling simulations

  # The remaining entries in this section are optional, but recommended.
  description: |
    OpenPathSampling is a library for trajectory-based rare events
    simulations, including transition path sampling, transition interface
    sampling, and committor simulations. Note that for real-world usage, you
    must also install one of the powerful molecular dynamics engines that
    OPS interfaces with, such as OpenMM or Gromacs. If you install those
    seprately, OPS will automatically support your installation of them.
  doc_url: https://openpathsampling.org
  dev_url: https://github.com/openpathsampling/openpathsampling

extra:
  recipe-maintainers:
    - dwhswenson
