{% set name = "openpathsampling" %}
{% set version = "1.5.2" %}
{% set sha256 = "beb8b2cde0f03d8746e244f9a22312277278cb3d9b4c602310562fa9a36de37c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  # note to self: if we add win support, switch skip line to noarch: python
  skip: true  # [win]
  script: MPLBACKEND=Agg {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - psutil
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - networkx
    - netcdf4
    - svgwrite
    - ujson !=2.*,!=3.*,!=4.0.0,!=4.0.1
    - mdtraj

test:
  imports:
    - openpathsampling

about:
  home: https://github.com/openpathsampling/openpathsampling
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for path sampling simulations

  # The remaining entries in this section are optional, but recommended.
  description: |
    OpenPathSampling is a library for trajectory-based rare events
    simulations, including transition path sampling, transition interface
    sampling, and committor simulations. Note that for real-world usage, you
    must also install one of the powerful molecular dynamics engines that
    OPS interfaces with, such as OpenMM or Gromacs. If you install those
    seprately, OPS will automatically support your installation of them.
  doc_url: https://openpathsampling.org
  dev_url: https://github.com/openpathsampling/openpathsampling

extra:
  recipe-maintainers:
    - dwhswenson
